### ISSUE TITLE
Modularize Content Search

### ISSUE THREAD

**Issue by kamsar** [blipson89/Synthesis#36]
The ContentSearch aspects of Synthesis should act on a plugin basis. This will ease the addition of Solr, and remove Lucene dependencies from the core.

Ref: #21

**Comment by fuzzyducky** [comment]
Hi Kam,

A few of us have been using Synthesis for a Sitecore 8 project, and so far we love it! The auto-gen of models is really great. 

We have reached a point in our project where we are trying to integrate with Solr, since we will be running on a scaled environment. It looks like you have been thinking about what it means to do this. I'm curious, do you have a timeline on getting synthesis to work with Solr? If not, would you have any suggestions / getting started tips on how we would go about using Synthesis with Solr?

Thanks again the awesome tool and any help you are willing to provide!

**Comment by kamsar** [comment]
There is a [partially complete PR](https://github.com/kamsar/Synthesis/pull/21) about adding Solr support. I've run up against the issue as we're using Solr as well these days, but haven't got around to it. If you'd like to hack on that PR, which I think is 60% or so complete, you're more than welcome.

However as a larger issue, while transparently promoting search instances is convenient it is also sometimes less than transparent about promotions occurring - or out of date indexes can cause unexpected failures to promote if the item does not exist in the database. This limits the usage of the content search support.

In some future state I am considering generating parallel, content-search-only models but we're not there yet.

**Comment by blipson89** [comment]
Heh. I did this work but completely forgot this PR existed.
