### ISSUE TITLE
Sitecore namespace conflicts

### ISSUE THREAD

**Issue by mattbarry** [blipson89/Synthesis#98]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
The generated models reference the Sitecore.ContentSearch and Sitecore.Data namespaces directly. I'm in the unfortunate situation of inheriting a Helix-like project that has chosen a namespace of _Org.Sitecore.Feature.Module_. So when Synthesis references the Sitecore namespace the compiler thinks it is referring to the project namespace and compilation fails. Much of my codebase aliases the Sitecore namespace to something like _SC_, but I can't do that with the Synthesis-generated code.

**What is the expected behavior?**

The desired behaviour might reference global::Sitecore.ContentSearch and global::Sitecore.Data, similar to the way the searchFields constructor in concrete model classes references global::System.Collections.Generic.IDictionary. I would be happy to submit a PR if this sounds like a desirable solution.

**Please mention your Sitecore version and Synthesis version.**
Sitecore 9.3.0 and Synthesis 9.1.2.1

**Comment by blipson89** [comment]
Your best bet for this situation would be to use [Leprechaun](https://github.com/blipson89/Leprechaun) for code generation, if that's an option.

I am planning another Synthesis release next week. If you'd like to submit a PR to add `global::`, I _think_ it would be in [CodeDomGenerator.cs](https://github.com/blipson89/Synthesis/blob/master/Source/Synthesis/Generation/CodeDom/CodeDomGenerator.cs), but it's been a loooooong time since I've touched that code. If you don't want to submit a PR for it, I can also take a peek this weekend. 

Leprechaun's code generator is a LOT more flexible and is designed to work with Synthesis out of the box.

**Comment by mattbarry** [comment]
Awesome. Thanks @blipson89! I had a look at the Synthesis code last night and it does indeed look like I could just update CodeDomGenerator.cs. I'll try to get a PR submitted, but I'll look into Leprechaun as well.

I really appreciate your suggestions!

**Comment by blipson89** [comment]
Released in [9.1.4](https://github.com/blipson89/Synthesis/releases/tag/9.1.4) - thank you for the help!
